### ISSUE TITLE
Pore.store() isn't generating the required .itp files.

### ISSUE THREAD

**Issue by CalenLev** [Ajax23/PoreMS#27]
When saving a pore object with pore.store(), the resulting pore.top file requires .itp files for all the attached molecules; however, these .itp files aren't being generated.

**Comment by Ajax23** [comment]
The store function only generates a master topology and a grid topology file. The latter contains the parameters for the grid molecules (SI, OM, SLX) and silanol groups (SL, SLG). 

If you attach other structures, e.g. TMS, you will have to provide the topologies yourself. First, we do not assume the topologies the user intends to utilize, and second, generating topology files would require a parameterization suite, which is not included in this package. Here it is suggested to use software such as Antechamber. Exemplary topologies are provided [in the documentation website](https://ajax23.github.io/PoreMS/workflow.html#simulation-folder-structure) (Here you can download an exemplary simulation structure containing the topology files).
