### ISSUE TITLE
generate non_silica pores

### ISSUE THREAD

**Issue by kamikahzadi** [Ajax23/PoreMS#29]
Hi, 

Is it possible to create nanopores with a different molecule to silica?

Thanks in advance

**Comment by Ajax23** [comment]
Hello,

sadly this is not currently possible without additional programming effort. Theoretically, the necessary functions exist but must be adjusted for other materials since silica is intrinsically implemented.

I have created a new feature request for future development.

**Comment by kamikahzadi** [comment]
Thank you for your response.
